name: GIFify

on:
  workflow_dispatch:
    inputs:
      video:
        description: 'Path to input video in repo'
        required: true
        default: 'earth.MOV'
      fps:
        description: 'Frames per second'
        required: false
        default: '30'
      width:
        description: 'Output width'
        required: false
        default: '320'

jobs:
  build-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg gifski coreutils

      - name: Run conversion script
        run: |
          #!/bin/sh
          set -eu

          # Input from workflow dispatch
          IN_VIDEO="${{ github.event.inputs.video }}"
          FPS="${{ github.event.inputs.fps }}"
          WIDTH="${{ github.event.inputs.width }}"

          echo "🎥 Input video: $IN_VIDEO"
          [ -f "$IN_VIDEO" ] || { echo "❌ File not found: $IN_VIDEO"; exit 1; }

          BASE_NAME=$(basename "$IN_VIDEO")
          OUT_GIF="${BASE_NAME%.*}_${WIDTH}px_${FPS}fps.gif"
          echo "🔧 Output GIF: $OUT_GIF"

          WORKDIR="$(pwd)/_gifski_tmp"
          FRAMES_DIR="$WORKDIR/frames"
          PALETTE="$WORKDIR/palette.png"
          mkdir -p "$FRAMES_DIR"

          echo "🔍 Generating palette..."
          ffmpeg -v error -i "$IN_VIDEO" \
            -vf "fps=$FPS,scale=$WIDTH:-1:flags=lanczos,palettegen" \
            -y "$PALETTE"

          echo "🎨 Encoding GIF with gifski..."
          gifski --fps "$FPS" --quality 100 --extra -o "$OUT_GIF" \
            "$FRAMES_DIR"/frame_*.png || \
          {
            echo "❌ gifski failed, falling back to ffmpeg paletteuse..."
            ffmpeg -v error -i "$IN_VIDEO" -i "$PALETTE" \
              -filter_complex "fps=$FPS,scale=$WIDTH:-1:flags=lanczos[x];[x][1:v]paletteuse" \
              -y "$OUT_GIF"
          }

          echo "✅ Created $OUT_GIF"

      - name: Upload GIF artifact
        uses: actions/upload-artifact@v3
        with:
          name: gif
          path: "*.gif"
